### ISSUE TITLE
deaths at 30d and 180d

### ISSUE THREAD

**Issue by edward-burn** [edward-burn/CharacterisationAndPlpECMO#11]
In the MDCD results the numbers for deaths are all the same, seems like there is an issue here somewhere.....

@anthonysena can you have a look at this please?

**Comment by anthonysena** [comment]
@edward-burn So in MDCD, all of the deaths happen at <= 30d which also means they happen at <= 180d. So, we could ammend the rule so that we are looking at 0-30d and then 31d-180d. Let me know what you think.
